name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Extract EmailJS Keys
        id: extract_keys
        run: |
          # Read the keys from the secret
          KEYS="${{ secrets.SOCAILS_LP_KEYS }}"
          
          # Extract individual values and clean them
          PUBLIC_KEY=$(echo "$KEYS" | grep "EMAILJS_PUBLIC_KEY:" | sed 's/.*: "\(.*\)"/\1/')
          SERVICE_ID=$(echo "$KEYS" | grep "EMAILJS_SERVICE_ID:" | sed 's/.*: "\(.*\)"/\1/')
          TEMPLATE_ID=$(echo "$KEYS" | grep "EMAILJS_TEMPLATE_ID:" | sed 's/.*: "\(.*\)"/\1/')
          
          # Debug output (without exposing actual values)
          echo "Extracted keys (showing length):"
          echo "PUBLIC_KEY length: ${#PUBLIC_KEY}"
          echo "SERVICE_ID length: ${#SERVICE_ID}"
          echo "TEMPLATE_ID length: ${#TEMPLATE_ID}"
          
          # Debug first character of each value (to verify no extra spaces or characters)
          echo "First characters:"
          echo "PUBLIC_KEY starts with: ${PUBLIC_KEY:0:1}"
          echo "SERVICE_ID starts with: ${SERVICE_ID:0:1}"
          echo "TEMPLATE_ID starts with: ${TEMPLATE_ID:0:1}"
          
          # Create config.js with cleaned values
          cat > config.js << EOL
          window.EMAILJS_CONFIG = {
            PUBLIC_KEY: "${PUBLIC_KEY}",
            SERVICE_ID: "${SERVICE_ID}",
            TEMPLATE_ID: "${TEMPLATE_ID}"
          };
          EOL
          
      - name: Debug Config
        run: |
          echo "Checking config.js format (without exposing secrets):"
          cat config.js | sed 's/\(PUBLIC_KEY\|SERVICE_ID\|TEMPLATE_ID\): "[^"]*"/\1: "[HIDDEN]"/g'
          
      - name: Update HTML paths
        run: |
          find . -type f -name "*.html" -exec sed -i 's|href="/|href="./|g' {} +
          find . -type f -name "*.html" -exec sed -i 's|src="/|src="./|g' {} +
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 